name: Deploy to GitHub Pages (gh-pages branch)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (for potential asset tools)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          user_name: 'github-actions'
          user_email: 'github-actions@github.com'
