name: Publish to GitHub Pages

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup pages
        uses: actions/configure-pages@v3
      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
